music_up_down_load/urls.py
"""" Βάζουμε τα url που σχετίζονται με το music_up_down_load app(m_u_d_l) τα οποία θα κάνουμε import στο urls.py του
musician_finder . Στην 10 κάνουμε home-page την m_u_d_l και της δίνουμε από το view το index"""

from django.urls import path, re_path

# Από τον current directory(music_up_down_load) βρές το αρχείο views και κάντο import
from . import views

app_name = 'music_up_down_load'

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^(?P<album_id>[0-9]+)$', views.details, name='details'),
    re_path(r'^(?P<album_id>[0-9]+)/favorite$', views.favorite, name='favorite'),
    re_path(r'^album-add$', views.AlbumCreate.as_view(), name='album-add'),

]

musician_finder/urls.py
# πχ1 Αν ο χρήστης κάνει search "admin" τότε πήγαινέ τον στο admin.site.urls

from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from users_core import views as user_view


urlpatterns = [

    path('admin/', admin.site.urls),
    path('music/', include('music_up_down_load.urls'), name='music_up_down_load'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('user/', include('users_core.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
    path('profile/', user_view.profile, name='profile'),
    path('upload/', user_view.upload, name='upload'),
    path('song_list/', user_view.composition_list, name='song_list'),
    path('song_list/upload', user_view.upload_song, name='upload_song'),
    path('lyrics_list/',user_view.lyrics_list, name='lyrics_list'),
    path('lyrics_list/upload', user_view.upload_lyrics, name='upload_lyrics'),
    path('search/', user_view.profile_search, name='profile_search'),
    path('profile/<int:prof_id>', user_view.profile_appearance, name='profile_appearance'),
    path('messages/', include('postman.urls')),
    path('song_delete/<int:song_id>', user_view.song_delete, name='song_delete'),
    path('lyric_delete/<int:lyric_id>',  user_view.lyric_delete, name='lyric_delete'),
    path('song_list/<int:prof_id>', user_view.other_composition_list, name='other_song_list'),
    path('lyrics_list/<int:prof_id>', user_view.other_lyrics_list, name='other_lyrics_list'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



users_core/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'users_core'

urlpatterns = [
    path('signup/', views.signup, name='signup'),

]

music_up_down_load/models.py
from django.db import models
from django.urls import reverse
""" Στη 7 δηλώνουμε τι τύπου δεδομένα μπορεί να έχει το column artist(πάντα βάζουμε max_length) """
# Create your models here.  Τρόπος αποθήκευσης δεδομένων δλδ πίνακες της βάσης δεδομένων(title,artist κλπ)


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)
    objects = models.Manager()

    def get_absolute_url(self):
        return reverse('music_up_down_load:details', kwargs={'album_id': self.pk})

    def __str__(self):
        return "%s - %s" % (self.artist, self.album_title)


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title




music_up_down_load/forms.py
from django import forms
from .models import User1


class User1Form(forms.ModelForm):
    Password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User1
        fields = ['Name', 'Surname', 'Username', 'Password', 'Email']

music_up_down_load/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView
from .models import Album, Song


def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music_up_down_load/index.html', {'all_albums': all_albums})


def details(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music_up_down_load/details.html', {'album': album})


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'music_up_down_load/details.html', {'album': album, 'error_message': "Unvalid song"})
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music_up_down_load/details.html', {'album': album})


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']





music_up_down_load/templates/music_up_down_load/album_form.html
{% block title %}Add Album{% endblock %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% block body %}
    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music_up_down_load/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

music_up_down_load/templates/music_up_down_load/details.html
<img src="{{ album.album_logo }}" height="200" width="200">

<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist }}</h2>

{%if error_message%}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music_up_down_load:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
               <img src="https://i.stack.imgur.com/LQk8v.png" height="20" width="20" />
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite" />
</form>

music_up_down_load/templates/music_up_down_load/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.error }}</span>

        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div class = "col-sm-10">{{ field }}</div>

    </div>
{% endfor %}

music_up_down_load/templates/music_up_down_load/index.html
<!--load the path to the static files -->
{% load static %}
<!--Αναφορά στο static αρχείο -->
 <link href="{% static 'music_up_down_load/css/style.css' %}" rel="stylesheet">
<!--Αναφορά στο bootstrap -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% if all_albums %}
    <h3>Here are  albums</h3>
    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music_up_down_load:details' album.id %}" >{{ album.album_title }} {{ album.artist }}</a></li>
        {% endfor %}
    </ul>
    <br>
    <a href="{% url 'music_up_down_load:album-add' %}">Add album</a>
{% else %}

    <h3>You don't have any albums</h3>
{% endif %}




music_up_down_load/templates/music_up_down_load/registration_form.html
{% block title %}Registration{% endblock %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% block body %}
    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel body">
                        <h3>Create New Account</h3>
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'music_up_down_load/form-template.html' %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}