musician_finder/urls.py
# πχ1 Αν ο χρήστης κάνει search "admin" τότε πήγαινέ τον στο admin.site.urls

from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from users_core import views as user_view


urlpatterns = [

    path('admin/', admin.site.urls),
    path('music/', include('music_up_down_load.urls'), name='music_up_down_load'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('user/', include('users_core.urls')),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
    path('profile/', user_view.profile, name='profile'),
    path('upload/', user_view.upload, name='upload'),
    path('song_list/', user_view.composition_list, name='song_list'),
    path('song_list/upload', user_view.upload_song, name='upload_song'),
    path('lyrics_list/',user_view.lyrics_list, name='lyrics_list'),
    path('lyrics_list/upload', user_view.upload_lyrics, name='upload_lyrics'),
    path('search/', user_view.profile_search, name='profile_search'),
    path('profile/<int:prof_id>', user_view.profile_appearance, name='profile_appearance'),
    path('messages/', include('postman.urls')),
    path('song_delete/<int:song_id>', user_view.song_delete, name='song_delete'),
    path('lyric_delete/<int:lyric_id>',  user_view.lyric_delete, name='lyric_delete'),
    path('song_list/<int:prof_id>', user_view.other_composition_list, name='other_song_list'),
    path('lyrics_list/<int:prof_id>', user_view.other_lyrics_list, name='other_lyrics_list'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



users_core/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'users_core'

urlpatterns = [
    path('signup/', views.signup, name='signup'),

]

users_core/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from multiselectfield import MultiSelectField
from django.conf import settings
import django_filters
from django import forms
from django.core.validators import FileExtensionValidator


YEARS = [x for x in range(1940, 2019)]


class Profile(models.Model):
    ROCK_CHOICES = (
        ('Classic Rock', 'Classic Rock'),
        ('Progressive Rock', 'Progressive Rock'),
        ('Post Rock', 'Post Rock'),
        ('Rock&Roll', 'Rock&Roll'),
        ('Psychedelic Rock', 'Psychedelic Rock'),
        ('Hard Rock', 'Hard Rock'),
        ('Garage Rock', 'Garage Rock'),
        ('Surf Rock', 'Surf Rock'),
        ('Rockabilly', 'Rockabilly'),
    )
    METAL_CHOICES = (
        ('Black Metal', 'Black Metal'),
        ('Death Metal', 'Death Metal'),
        ('Thrash Metal', 'Thrash Metal'),
        ('Doom Metal', 'Doom Metal'),
        ('Progressive Metal', 'Progressive Metal'),
        ('Sludge Metal', 'Sludge Metal'),
        ('Heavy Metal', 'Heavy Metal'),
        ('Metalcore', 'Metalcore'),
        ('Grindcore', 'Grindcore'),
    )
    PUNK_CHOICES = (
        ('Punk Rock', 'Punk Rock'),
        ('Pop Punk', 'Pop Punk'),
        ('Garage Punk', 'Garage Punk'),
        ('Hardcore Punk', 'Hardcore Punk'),
        ('Thrash Punk', 'Thrash Punk'),
        ('Crust Punk', 'Crust Punk'),
        ('Folk Punk', 'Folk Punk'),
        ('Ska Punk', 'Ska Punk'),
    )
    POP_CHOICES = (
        ('Indie Pop', 'Indie Pop'),
        ('Synth Pop', 'Synth Pop'),
        ('Power Pop', 'Power Pop'),
        ('Dream Pop', 'Dream Pop'),
        ('Noise Pop', 'Noise Pop'),
        ('Experimental Pop', 'Experimental Pop'),
        ('Jangle Pop', 'Jangle Pop'),
    )
    BLUES_CHOICES = (
        ('Blues', 'Blues'),
        ('Blues Rock', 'Blues Rock'),
        ('Country Blues', 'Country Blues'),
        ('Rythm & Blues', 'Rythm & Blues'),
        ('Electric Blues', 'Electric Blues'),
        ('Boogie-Woogie', 'Boogie-Woogie'),
        ('Bluegrass', 'Bluegrass'),
        ('Delta Blues', 'Delta Blues'),
    )
    JAZZ_CHOICES = (
        ('Jazz', 'Jazz'),
        ('Nu Jazz', 'Nu Jazz'),
        ('Modern Jazz', 'Modern Jazz'),
        ('Free Jazz', 'Free Jazz'),
        ('Soul Jazz', 'Soul Jazz'),
        ('Swing', 'Swing'),
        ('Latin Jazz', 'Latin Jazz'),
        ('Vocal Jazz', 'Vocal Jazz'),
        ('Spiritual Jazz', 'Spiritual Jazz'),
    )
    FUNK_CHOICES = (
        ('Funk', 'Funk'),
        ('Funk Jam', 'Funk Jam'),
        ('Deep Funk', 'Deep Funk'),
        ('Funk Rock', 'Funk Rock'),
        ('Jazz Funk', 'Jazz Funk'),
        ('g-Funk', 'g-Funk'),
        ('Electro Funk', 'Electro Funk'),
        ('Go-go', 'Go-go'),
    )
    SOUL_CHOICES = (
        ('Soul', 'Soul'),
        ('Neo-Soul', 'Neo-Soul'),
        ('Gospel', 'Gospel'),
    )
    ELECTRONIC_CHOICES = (
        ('House', 'House'),
        ('Electronica', 'Electronica'),
        ('Downtempo', 'Downtempo'),
        ('Techno', 'Techno'),
        ('Electro', 'Electro'),
        ('Dubstep', 'Dubstep'),
        ('Drum % Bass', 'Drum & Bass'),
        ('Trance', 'Trance'),
        ('Dub', 'Dub'),
        ('Vaporwave', 'Vaporwave'),
    )

    HIP_HOP_RAP_CHOICES = (
        ('Rap', 'Rap'),
        ('Trap', 'Trap'),
        ('Instrumental Hip-Hop', 'Instrumental Hip-Hop'),
        ('Boom-Bap', 'Boom-Bap'),
        ('Beat-tape', 'Beat-tape'),
    )
    GREEK_CHOICES = (
        ('Έντεχνο', 'Έντεχνο'),
        ('Λαϊκό', 'Λαϊκό'),
        ('Ρεμπέτεκο', 'Ρεμπέτεκο'),
    )

    OTHER_CHOICES = (
        ('Ska', 'Ska'),
        ('No Wave', 'No Wave'),
        ('Folk', 'Folk'),
        ('New wave', 'New wave'),
        ('Swing', 'Swing'),
        ('Gospel', 'Gospel'),
    )

    MUSIC_NATURE = (
        ('Drummer', 'Drummer'),
        ('Τραγουδιστής', 'Τραγουδιστής'),
        ('Κιθαρίστας', 'Κιθαρίστας'),
        ('Μπασίστας', 'Μπασίστας'),
        ('Στιχουργός', 'Στιχουργός '),
        ('Σαξοφωνίστας', 'Σαξοφωνίστας '),
        ('Κλαριτζής', 'Κλαριτζής '),
        ('Dj', 'Dj '),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    rock = MultiSelectField(choices=ROCK_CHOICES, blank=True)
    metal = MultiSelectField(choices=METAL_CHOICES, blank=True)
    punk = MultiSelectField(choices=PUNK_CHOICES, blank=True)
    pop = MultiSelectField(choices=POP_CHOICES, blank=True)
    blues = MultiSelectField(choices=BLUES_CHOICES, blank=True)
    jazz = MultiSelectField(choices=JAZZ_CHOICES, blank=True)
    funk = MultiSelectField(choices=FUNK_CHOICES, blank=True)
    soul = MultiSelectField(choices=SOUL_CHOICES, blank=True)
    electronic = MultiSelectField(choices=ELECTRONIC_CHOICES, blank=True)
    hiphop_rap = MultiSelectField(choices=HIP_HOP_RAP_CHOICES, blank=True)
    greek = MultiSelectField(choices=GREEK_CHOICES, blank=True)
    other = MultiSelectField(choices=OTHER_CHOICES, blank=True)
    music_nature = MultiSelectField(choices=MUSIC_NATURE, blank=True)
    birth_date = models.DateField(blank=True, null=True)
    objects = models.Manager()

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class Song(models.Model):
    composition_title = models.CharField(max_length=100, blank=True)
    composition = models.FileField(upload_to='uploaded_music', max_length=100, blank=True,
                                   validators=[FileExtensionValidator(allowed_extensions=['mp3', 'flac', 'wav'])])
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    is_public = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.composition_title} composition'


class Lyrics(models.Model):
    lyrics_title = models.CharField(max_length=100, blank=True)
    lyrics = models.FileField(upload_to='uploaded_lyrics', max_length=100, blank=True,
                              validators=[FileExtensionValidator(allowed_extensions=['pdf'])])
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return f'{self.lyrics_title} lyrics'

templates/base.html
 {% load static %}
<!-- templates/base.html -->

<html>
<head>

  <meta charset="utf-8">
  <title>{% block title %}Django Tutorial{% endblock %}</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">


<style>

* {
  box-sizing: border-box;
}

#navbar{

  width: 100%;
  height: 70px;
  background-color:  rgba(    0, 0, 0   , 0.8) ;
  overflow: hidden;
  position:fixed;
  z-index:1

}

.content {
  padding-top: 0px;

}

li{
    list-style:none;
    display:inline;
    margin-right:20;
    color:white;
    background: none;

}

ul:not([id]) li{
    color:black;
    display:list-item;
}


ul#id_music_nature li {
  display:inline;
  margin-right:20;
}

p{
color:black;
}



.li_background_color{
    background-color:white;
    color:black ;
    border-radius: 6px;
    font-size:20px;
    font-family:serif;
}

.li_background_color2{
    background-color:blue;
    color:white ;
    border-radius: 6px;
    font-size:20px;
    font-family:serif;
}

input[type=text] {
  width: 30%;
  padding: 12px 20px;
  box-sizing: border-box;
  border: 2px solid #40E0D0;;
  border-radius: 4px;
  font-size:20px;
}

input[type=password] {
  width: 30%;
  padding: 12px 20px;
  box-sizing: border-box;
  border: 2px solid #40E0D0;;
  border-radius: 4px;
  font-size:20px;
}

input[type=email] {
  width: 30%;
  padding: 12px 20px;
  box-sizing: border-box;
  border: 2px solid #40E0D0;
  border-radius: 4px;
  font-size:20px;
}


.sticky {
  position: fixed;
  top: 0;
  width: 100%;
}



.nav_block{

    display: block;
    float: left;
    font-family: sans-serif;
    font-size: 19px;
    color: white;


    padding-top: 15px;
    padding-right: 10px;
    padding-bottom: 10px;
    padding-left: 10px;
    text-decoration: none;
    margin-top:5px;
    margin-left:20px;
    transition-property: color;
    transition-duration: 0.3s;
}

div a:hover{

    color: #ff6400;
    text-decoration: none;
}

music_list {

}


.username{
    color: #00008B;
    text-decoration: none;
    transition-property: color;
    transition-duration: 0.3s;
}

.username:hover{

    color: #ff6400;
    text-decoration: none;
}

div a:active {
  color: #0004ff;
}

.myButton {
	-moz-box-shadow: 0px 10px 14px -7px #276873;
	-webkit-box-shadow: 0px 10px 14px -7px #276873;
	box-shadow: 0px 10px 14px -7px #276873;
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #599bb3), color-stop(1, #408c99));
	background:-moz-linear-gradient(top, #599bb3 5%, #408c99 100%);
	background:-webkit-linear-gradient(top, #599bb3 5%, #408c99 100%);
	background:-o-linear-gradient(top, #599bb3 5%, #408c99 100%);
	background:-ms-linear-gradient(top, #599bb3 5%, #408c99 100%);
	background:linear-gradient(to bottom, #599bb3 5%, #408c99 100%);
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#599bb3', endColorstr='#408c99',GradientType=0);
	background-color:#599bb3;
	-moz-border-radius:8px;
	-webkit-border-radius:8px;
	border-radius:8px;
	display:inline-block;
	cursor:pointer;
	color:#ffffff;
	font-family:Arial;
	font-size:20px;
	font-weight:bold;
	padding:13px 32px;
	text-decoration:none;
	text-shadow:0px 1px 0px #3d768a;
}
.myButton:hover {
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #408c99), color-stop(1, #599bb3));
	background:-moz-linear-gradient(top, #408c99 5%, #599bb3 100%);
	background:-webkit-linear-gradient(top, #408c99 5%, #599bb3 100%);
	background:-o-linear-gradient(top, #408c99 5%, #599bb3 100%);
	background:-ms-linear-gradient(top, #408c99 5%, #599bb3 100%);
	background:linear-gradient(to bottom, #408c99 5%, #599bb3 100%);
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#408c99', endColorstr='#599bb3',GradientType=0);
	background-color:#408c99;
	color: #b3bcc0
}
.myButton:active {
	position:relative;
	top:1px;
}

.button3{
-moz-box-shadow: 0px 10px 14px -7px #276873;
	-webkit-box-shadow: 0px 10px 14px -7px #276873;
	box-shadow: 0px 10px 14px -7px #276873;
	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #599bb3), color-stop(1, #408c99));
	background:-moz-linear-gradient(top, #000000 5%, #408c99 100%);
	background:-webkit-linear-gradient(top, #599000000 5%, #408c99 100%);
	background:-o-linear-gradient(top, #000000 5%, #408c99 100%);
	background:-ms-linear-gradient(top, #000000 5%, #408c99 100%);
	background:linear-gradient(to bottom, #000000 5%, #408c99 100%);
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#000000', endColorstr='#408c99',GradientType=0);
	background-color:#599bb3;
	-moz-border-radius:8px;
	-webkit-border-radius:8px;
	border-radius:8px;
	display:inline-block;
	cursor:pointer;
	color:#ffffff;
	font-family:Arial;
	font-size:20px;
	font-weight:bold;
	padding:13px 32px;
	text-decoration:none;
	text-shadow:0px 1px 0px #3d768a;
	margin-top:20px;
}
.button3:hover{
 	background:-webkit-gradient(linear, left top, left bottom, color-stop(0.05, #408c99), color-stop(1, #599bb3));
	background:-moz-linear-gradient(top, #000000 5%, #599bb3 100%);
	background:-webkit-linear-gradient(top, #000000 5%, #599bb3 100%);
	background:-o-linear-gradient(top, #000000 5%, #599bb3 100%);
	background:-ms-linear-gradient(top, #000000 5%, #599bb3 100%);
	background:linear-gradient(to bottom, #000000 5%, #599bb3 100%);
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#000000', endColorstr='#599bb3',GradientType=0);
	background-color:#000000;
	color: #b3bcc0
}

.button3:active{
	position:relative;
	top:1px;
}

.button4 {
color: black !important;
text-transform: none;
background: #ffffff;
padding: 15px;
border: 4px solid #494949 !important;
border-radius: 6px;
display: inline-block;
}

.button4:hover {
color: #ffffff !important;
background: #f6b93b;
border-color: #f6b93b !important;
transition: all 0.4s ease 0s;
}

.anim{

  position: relative;
  animation: mymove 0.3s;
  animation-iteration-count: 1;
}


@keyframes mymove {
 0% { opacity:0; }
 50% { opacity:1; }
 100% { opacity:0; }
}



#submit_profile{
color:black;}

.results_p{
    color:black;
    font-size:15px;
    padding-top:5px;
}

.download{
    background-color:#00275E;
    height:30px;
    width:100px;
     transition-property: box-shadow;
    transition-duration: 0.3s;
    border-radius: 25px;
}

.download:hover{
    box-shadow: inset 0 0 100px 100px rgba(255, 255, 255, 0.1);
}

.delete{
    background-color:#bb000e;
    height:30px;
    width:100px;
    transition-property: box-shadow;
    transition-duration: 0.3s;
    border-radius: 25px;
}

.p_in_box{
    text-align:center;
    color:white;
    font-size:15px;
    padding-top:3px;
}

.delete:hover{
    box-shadow: inset 0 0 100px 100px rgba(255, 255, 255, 0.1);
}


body{
        }
</style>
</head>
<body>

        <div id="navbar">

            <a id="logo" href="{% url 'home' %}" style="float:left; margin-right:50px"><img src="{% static 'images/base_logo.jpg' %}" height="80px" width="100px"></a>
            <a class="nav_block" href="{% url 'profile_search' %}">Αναζήτηση</a>
            <a class="nav_block" href=" {% url 'profile' %}  ">Προφίλ</a>
            <a class="nav_block" href=" {% url 'song_list' %} ">Συνθέσεις({{ user.song_set.count }})</a>
            <a class="nav_block" href=" {% url 'lyrics_list' %}">Στίχοι ({{ user.lyrics_set.count }})</a>
            <a class="nav_block" style="margin-left:500px; " href="{% url 'logout' %}">Αποσύνδεση</a>

        </div>



        <div class="content" >
            {% block content %}
            {% endblock %}
        </div>



</body>
</html>

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}Αρχική σελίδα{% endblock %}

{% block content %}


{% if user.is_authenticated %}

    <div style="height:630px;margin-top:0px; background-size: 100%;
      background-image: url({% static 'images/musicians1.jpg' %});" >
        <div align="center" style="padding-top:200px"><h1 style="color: #0892D0; font-style: oblique; font-weight: 900;">Εδώ θα βρείς
            τους μουσικούς που ψάχνεις!!</h1></div>

        <div align="center" style="padding-top:30px">
            <a href="{% url 'profile_search' %}" class="myButton" >Βρές μουσικούς</a>
        </div>

      </div>


{% else %}
<div   align="center"  style="background-image: url({% static 'images/musicians7.jpg' %});  background-size:100%; height:630px">
    <div style="">
    <p style="padding-top:50px; font-size:20px; color:white;">Καλώς ήρθατε στο <br>
        <span style="color:red;">Musician Finder</span><br>Εδώ μπορείτε να:<br>1) Βρείτε μουσικούς <br>
        2) Σας βρούν μουσικοί <br> 3) Ανταλλάξετε μηνύματα, συνθέσεις και στίχους <br>
        <span>Αν έχετε λογαριασμό <a href="{% url 'login' %}">Σύνδεθείτε</a> αλλίως κάντε
        <a href="{% url 'users_core:signup' %}">Εγγραφή</a> </span>
        </p>
        </div>

</div>
<script>
  document.getElementById("navbar").style.visibility = "hidden";
</script>

{% endif %}


{% endblock %}

templates/lyric_delete.html
{% extends 'base.html' %}


{% block content %}
<div style="padding-top:100px" align="center">

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Εϊστε σιγουροι ότι θέλετε να διαγράψετε το "{{ lyric }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-warning">
        <a href="{% url 'lyrics_list' %}" class="btn btn-default">Ακύρωση</a>
    </form>

</div>

{% endblock %}

templates/other_lyrics_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Στίχοι του/της {{ profile.user.username }}{% endblock %}
{% block content %}
{% if profile %}
<div style="background-color:#f2aa4cff; height:100%; width:100%;  padding-top:80px">

    <h3 style="color:black; padding-left:25px; padding-top:25px; padding-bottom: 70px; " >Στίχοι του/της {{ profile.user.username }}: ({{ profile.user.lyrics_set.count }})</h3>
    {% for lyrics in profile.user.lyrics_set.all %}

        <div style=" border: 15px solid #f2aa4cff; ">
        <div class="row" style=" height:50px; background-color:black;">
            <div class="col-lg-1" >
                <p style="color:white; text-align:center; font-size:20px;">{{ forloop.counter }}</p>
            </div>
             <div class="col-lg-11">
                 <p style="color:white; text-align:left; font-size:20px;">{{ lyrics.lyrics_title }}</p>
             </div>
        </div>
        <div class="row" style=" background-color:black; ">
                <div class="col-md-3" style=" padding-left:120px; ">
                    <div style="padding-bottom:9px;">
                    <a href="{{ lyrics.lyrics.url }}" class="btn btn-primary btn-sm" target="_blank" >Δες τους στίχους</a>
                        </div>
                </div>
            <div class="col-lg-8">
                <a href="{{ lyrics.lyrics.url }}" style="color:white;float:left; padding-left:150px;" target="_blank" download>
                        <div class="download"><p class="p_in_box">Κατέβασμα</p></div></a>
            </div>

        </div>
     </div>

    {% endfor %}


</div>

{% endif %}

{% endblock %}

templates/profile_appearance.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ profile.user.username }}{% endblock %}
{% block content %}
{% if profile %}
<div style="padding-top:70px;">
    <div style="background-image: linear-gradient(rgb( 40,40,40), rgb( 0, 0, 0));">
        <div class="container-fluid" style="height:200px; ">
                <div class="row">
                    <div class="col-lg-2" style="padding:25px;">
                        <img class="w3-round"  src="{{ profile.image.url }}" width="200" height="150"/>
                    </div>
                    <div class="col-lg-10" style="padding-left:50px;" >
                        <p style="color:white; padding-top:30px; font-size:30px;">{{ profile.user.username }}</p>
                        <p style="color:white;  font-size:20px;font-family: Times,Times New Roman, serif">{{ profile.user.email }}</p>
                        <p style="color:white;  font-size:20px;">{{ profile.user.first_name }} {{ profile.user.last_name }}</p>
                        <p style="color:white">{{ profile.id }}</p>
                    </div>
                </div>
        </div>
            <div>
                <p style="padding:25px; font-size:25px; color:#40E0D0;">Μουσικές ιδιότητες:<br>
                    <span id="music_n" style="font-size:20px; color:white;">{{ profile.music_nature }}</span></p>

                        <p style="padding:25px; margin-bottom:0px; font-size:25px; color: red ;">Μουσικά ακούσματα:<br>
                            <span id="music" style="font-size:20px; color:white;">
                                {% if profile.rock %}
                                <span style="color:red; ">Rock:</span> {{ profile.rock }}<br>
                                {% endif %}
                                {% if profile.metal %}
                                <span style="color:red;">Metal:</span> {{ profile.metal }}<br>
                                {% endif %}
                                {% if profile.punk %}
                                <span style="color:red;">Punk:</span> {{ profile.punk }}<br>
                                {% endif %}
                                {% if profile.pop %}
                                <span style="color:red;">Pop:</span> {{ profile.pop }}<br>
                                {% endif %}
                                {% if profile.blues %}
                                <span style="color:red;">Blues:</span> {{ profile.blues }}<br>
                                {% endif %}
                                {% if profile.jazz %}
                                <span style="color:red;">Jazz:</span> {{profile.jazz }}<br>
                                {% endif %}
                                {% if profile.funk %}
                                <span style="color:red;">Funk:</span> {{ profile.funk }}<br>
                                {% endif %}
                                {% if profile.soul %}
                                <span style="color:red;">Soul:</span> {{ profile.soul }}<br>
                                {% endif %}
                                {% if profile.electronic %}
                                <span style="color:red;">Electronic:</span> {{ profile.electronic }}<br>
                                {% endif %}
                                {% if profile.hiphop_rap %}
                                <span style="color:red;">Hiphop/Rap:</span> {{ profile.hiphop_rap }}<br>
                                {% endif %}
                                {% if profile.greek %}
                                <span style="color:red;">Greek:</span> {{ profile.greek }}<br>
                                {% endif %}
                                {% if profile.other %}
                                <span style="color:red;">Other:</span> {{ profile.other }}<br>
                                {% endif %}
                            </span></p>
            </div>
    </div>
            <div style="background-color:#161515;">
                <p style="color:white; padding-top:30px; padding-left:25px; font-family:cursive; font-size:30px;">Στοιχεία του προφίλ</p>
                         <div  style="padding-left:25px;">
                             <p style="color:white; padding-top:20px;  font-size:20px; ">Όνομα : {{ profile.user.first_name }}</p>
                             <p style="color:white; padding-top:20px; font-size:20px;">Επίθετο : {{profile.user.last_name }}</p>
                             <p style="color:white; padding-top:20px;  font-size:20px;">Email : {{ profile.user.email }}</p>
                             <p style="color:white; padding-top:20px;  font-size:20px;">Ημερομηνία Γέννησης: <td>{{ profile.birth_date}}</td></p><br>
                             <a href="{% url 'other_song_list' profile.id %}" style="font-family:cursive; font-size:30px; color:#RRGGBB; padding-top:20px; ">Συνθέσεις: ({{ profile.user.song_set.count }})</a><br><br>

                             <a href="{% url 'other_lyrics_list' profile.id %}" style="font-family:cursive; font-size:30px; color:#00FF00; padding-top:20px; margin-bottom:0px;">Στίχοι: ({{ profile.user.lyrics_set.count }})</a>

                          </div>

            </div>
</div>
{% endif %}


{% endblock %}

templates/rhymes.html
{% if user.is_authenticated %}

<h1>Rhymes</h1>

{% endif %}

templates/song_delete.html
{% extends 'base.html' %}


{% block content %}
<div style="padding-top:100px" align="center">

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Εϊστε σιγουροι ότι θέλετε να διαγράψετε το "{{ song }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-warning">
        <a href="{% url 'song_list' %}" class="btn btn-default">Ακύρωση</a>
    </form>

</div>

{% endblock %}

templates/upload.html
{% extends 'base.html' %}

{% block content %}
  <h2>Upload</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="document">
    <button type="submit">Upload file</button>
  </form>

{% if url %}
    <a href="{{ url }}"> Uploaded file</a>

{% endif %}
{% endblock %}